export const SELECT_GENRE = 'SELECT_GENRE';
export const SELECT_REALEASE_YEAR = 'SELECT_REALEASE_YEAR';
export const SELECT_RATING_FROM = 'SELECT_RATING_FROM';
export const SELECT_RATING_TO = 'SELECT_RATING_TO';
export const RESET_FILTERS = 'RESET_FILTERS';
export const SELECT_SORT_BY = 'SELECT_SORT_BY';
export const SELECT_PAGE = 'SELECT_PAGE';
